//***************************************
// user code copied to the file here.
//***************************************
package coho.interp;	//define the package
import java_cup.runtime.*;  	//import cup
import java.io.*;
//Usually, the default class name is Yylex, the default function name is yylex and the default return type is Yytoken
//We can change the default value by %class <name> %funciton <name> and %type<name> in the second part sepearately.
//1) We usually add user code for the definiation of return class. Here, we use Symbol from CUP.
//2) And also we define constants that corresponding to each token type. We use the definiation of Sym.java generated by cup.
//   And also we have a map provided by SymboleName.java.
//***************************************
// JLex Directives.
//***************************************


public class Scanner implements java_cup.runtime.Scanner {
	private final int YY_BUFFER_SIZE = 512;
	private final int YY_F = -1;
	private final int YY_NO_STATE = -1;
	private final int YY_NOT_ACCEPT = 0;
	private final int YY_START = 1;
	private final int YY_END = 2;
	private final int YY_NO_ANCHOR = 4;
	private final int YY_BOL = 128;
	private final int YY_EOF = 129;
	public final int YYEOF = -1;
				//user code copied to the class
	// map the string name to Symbol.
	private PTfactory pf;
	private SymbolName sname;
	private Symbol symbol(String name) {
	    int key = sname.nameToKey(name);
	    return(new Symbol(key, pf.create(key, yytext())));
	}
	// Constructor to initilize pf and sname.
	public Scanner(java.io.Reader reader, PTfactory _pf, SymbolName _sname) {
    	    this(reader);
    	    pf = _pf;
    	    sname = _sname;
  	}
  	// test file
  	public static void main(String args[]) throws Exception {
    	    PTfactory pf = new PTnodeFactory();
    	    SymbolName sname = new SymbolName();
    	    Scanner s = new Scanner(new InputStreamReader(System.in), pf, sname);
    	    PTnode pt;
    	    int endKey = sname.nameToKey("EOF");
    	    System.out.println("Scanner.main: start typing tokens");
	    do {
	      pt = (PTnode)(s.next_token().value);
	      System.out.print(pt+"\n");
	    } while(pt.key() != endKey);
     	}
	private java.io.BufferedReader yy_reader;
	private int yy_buffer_index;
	private int yy_buffer_read;
	private int yy_buffer_start;
	private int yy_buffer_end;
	private char yy_buffer[];
	private int yychar;
	private int yyline;
	private boolean yy_at_bol;
	private int yy_lexical_state;

	public Scanner (java.io.Reader reader) {
		this ();
		if (null == reader) {
			throw (new Error("Error: Bad input stream initializer."));
		}
		yy_reader = new java.io.BufferedReader(reader);
	}

	public Scanner (java.io.InputStream instream) {
		this ();
		if (null == instream) {
			throw (new Error("Error: Bad input stream initializer."));
		}
		yy_reader = new java.io.BufferedReader(new java.io.InputStreamReader(instream));
	}

	private Scanner () {
		yy_buffer = new char[YY_BUFFER_SIZE];
		yy_buffer_read = 0;
		yy_buffer_index = 0;
		yy_buffer_start = 0;
		yy_buffer_end = 0;
		yychar = 0;
		yyline = 0;
		yy_at_bol = true;
		yy_lexical_state = YYINITIAL;
	}

	private boolean yy_eof_done = false;
	private final int YYINITIAL = 0;
	private final int yy_state_dtrans[] = {
		0
	};
	private void yybegin (int state) {
		yy_lexical_state = state;
	}
	private int yy_advance ()
		throws java.io.IOException {
		int next_read;
		int i;
		int j;

		if (yy_buffer_index < yy_buffer_read) {
			return yy_buffer[yy_buffer_index++];
		}

		if (0 != yy_buffer_start) {
			i = yy_buffer_start;
			j = 0;
			while (i < yy_buffer_read) {
				yy_buffer[j] = yy_buffer[i];
				++i;
				++j;
			}
			yy_buffer_end = yy_buffer_end - yy_buffer_start;
			yy_buffer_start = 0;
			yy_buffer_read = j;
			yy_buffer_index = j;
			next_read = yy_reader.read(yy_buffer,
					yy_buffer_read,
					yy_buffer.length - yy_buffer_read);
			if (-1 == next_read) {
				return YY_EOF;
			}
			yy_buffer_read = yy_buffer_read + next_read;
		}

		while (yy_buffer_index >= yy_buffer_read) {
			if (yy_buffer_index >= yy_buffer.length) {
				yy_buffer = yy_double(yy_buffer);
			}
			next_read = yy_reader.read(yy_buffer,
					yy_buffer_read,
					yy_buffer.length - yy_buffer_read);
			if (-1 == next_read) {
				return YY_EOF;
			}
			yy_buffer_read = yy_buffer_read + next_read;
		}
		return yy_buffer[yy_buffer_index++];
	}
	private void yy_move_end () {
		if (yy_buffer_end > yy_buffer_start &&
		    '\n' == yy_buffer[yy_buffer_end-1])
			yy_buffer_end--;
		if (yy_buffer_end > yy_buffer_start &&
		    '\r' == yy_buffer[yy_buffer_end-1])
			yy_buffer_end--;
	}
	private boolean yy_last_was_cr=false;
	private void yy_mark_start () {
		int i;
		for (i = yy_buffer_start; i < yy_buffer_index; ++i) {
			if ('\n' == yy_buffer[i] && !yy_last_was_cr) {
				++yyline;
			}
			if ('\r' == yy_buffer[i]) {
				++yyline;
				yy_last_was_cr=true;
			} else yy_last_was_cr=false;
		}
		yychar = yychar
			+ yy_buffer_index - yy_buffer_start;
		yy_buffer_start = yy_buffer_index;
	}
	private void yy_mark_end () {
		yy_buffer_end = yy_buffer_index;
	}
	private void yy_to_mark () {
		yy_buffer_index = yy_buffer_end;
		yy_at_bol = (yy_buffer_end > yy_buffer_start) &&
		            ('\r' == yy_buffer[yy_buffer_end-1] ||
		             '\n' == yy_buffer[yy_buffer_end-1] ||
		             2028/*LS*/ == yy_buffer[yy_buffer_end-1] ||
		             2029/*PS*/ == yy_buffer[yy_buffer_end-1]);
	}
	private java.lang.String yytext () {
		return (new java.lang.String(yy_buffer,
			yy_buffer_start,
			yy_buffer_end - yy_buffer_start));
	}
	private int yylength () {
		return yy_buffer_end - yy_buffer_start;
	}
	private char[] yy_double (char buf[]) {
		int i;
		char newbuf[];
		newbuf = new char[2*buf.length];
		for (i = 0; i < buf.length; ++i) {
			newbuf[i] = buf[i];
		}
		return newbuf;
	}
	private final int YY_E_INTERNAL = 0;
	private final int YY_E_MATCH = 1;
	private java.lang.String yy_error_string[] = {
		"Error: Internal error.\n",
		"Error: Unmatched input.\n"
	};
	private void yy_error (int code,boolean fatal) {
		java.lang.System.out.print(yy_error_string[code]);
		java.lang.System.out.flush();
		if (fatal) {
			throw new Error("Fatal Error.\n");
		}
	}
	private int[][] unpackFromString(int size1, int size2, String st) {
		int colonIndex = -1;
		String lengthString;
		int sequenceLength = 0;
		int sequenceInteger = 0;

		int commaIndex;
		String workString;

		int res[][] = new int[size1][size2];
		for (int i= 0; i < size1; i++) {
			for (int j= 0; j < size2; j++) {
				if (sequenceLength != 0) {
					res[i][j] = sequenceInteger;
					sequenceLength--;
					continue;
				}
				commaIndex = st.indexOf(',');
				workString = (commaIndex==-1) ? st :
					st.substring(0, commaIndex);
				st = st.substring(commaIndex+1);
				colonIndex = workString.indexOf(':');
				if (colonIndex == -1) {
					res[i][j]=Integer.parseInt(workString);
					continue;
				}
				lengthString =
					workString.substring(colonIndex+1);
				sequenceLength=Integer.parseInt(lengthString);
				workString=workString.substring(0,colonIndex);
				sequenceInteger=Integer.parseInt(workString);
				res[i][j] = sequenceInteger;
				sequenceLength--;
			}
		}
		return res;
	}
	private int yy_acpt[] = {
		/* 0 */ YY_NOT_ACCEPT,
		/* 1 */ YY_NO_ANCHOR,
		/* 2 */ YY_NO_ANCHOR,
		/* 3 */ YY_NO_ANCHOR,
		/* 4 */ YY_NO_ANCHOR,
		/* 5 */ YY_NO_ANCHOR,
		/* 6 */ YY_NO_ANCHOR,
		/* 7 */ YY_NO_ANCHOR,
		/* 8 */ YY_NO_ANCHOR,
		/* 9 */ YY_NO_ANCHOR,
		/* 10 */ YY_NO_ANCHOR,
		/* 11 */ YY_NO_ANCHOR,
		/* 12 */ YY_NO_ANCHOR,
		/* 13 */ YY_NO_ANCHOR,
		/* 14 */ YY_NO_ANCHOR,
		/* 15 */ YY_NO_ANCHOR,
		/* 16 */ YY_NO_ANCHOR,
		/* 17 */ YY_NOT_ACCEPT,
		/* 18 */ YY_NO_ANCHOR,
		/* 19 */ YY_NO_ANCHOR,
		/* 20 */ YY_NOT_ACCEPT,
		/* 21 */ YY_NO_ANCHOR,
		/* 22 */ YY_NO_ANCHOR,
		/* 23 */ YY_NOT_ACCEPT,
		/* 24 */ YY_NO_ANCHOR,
		/* 25 */ YY_NOT_ACCEPT,
		/* 26 */ YY_NO_ANCHOR,
		/* 27 */ YY_NOT_ACCEPT
	};
	private int yy_cmap[] = unpackFromString(1,130,
"10:9,11,12,10,11:2,10:18,11,10:3,19,9,10,15,3,4,10,16,1,7,17,10,14:10,10,2," +
"10,8,10:3,13:4,18,13:21,5,10,6,10,13,10,20:4,21,20,13:20,10:5,0:2")[0];

	private int yy_rmap[] = unpackFromString(1,28,
"0,1:7,2,1,3,1,4,5,6,7,8,9,10,11,12,2,13,10,9,8,14,13")[0];

	private int yy_nxt[][] = unpackFromString(15,22,
"1,2,3,4,5,6,7,8,9,10,11,12:2,13,14,18,21,24,13,26,13:2,-1:36,14,-1:2,17,-1:" +
"5,10:11,-1,10:9,-1:11,12:2,-1:22,13:2,-1:3,13,-1,13:2,-1:14,14,-1:2,17,20,-" +
"1:2,20,-1:15,23,-1:20,16,-1:5,16:2,-1:14,19,-1:8,23:14,15,23:6,-1:14,19,-1:" +
"3,20,-1:2,20,-1:7,27,-1:6,22,-1,27,-1:19,22,-1:14,25,-1:6,16,-1,25,-1:3,16:" +
"2");

	public java_cup.runtime.Symbol next_token ()
		throws java.io.IOException {
		int yy_lookahead;
		int yy_anchor = YY_NO_ANCHOR;
		int yy_state = yy_state_dtrans[yy_lexical_state];
		int yy_next_state = YY_NO_STATE;
		int yy_last_accept_state = YY_NO_STATE;
		boolean yy_initial = true;
		int yy_this_accept;

		yy_mark_start();
		yy_this_accept = yy_acpt[yy_state];
		if (YY_NOT_ACCEPT != yy_this_accept) {
			yy_last_accept_state = yy_state;
			yy_mark_end();
		}
		while (true) {
			if (yy_initial && yy_at_bol) yy_lookahead = YY_BOL;
			else yy_lookahead = yy_advance();
			yy_next_state = YY_F;
			yy_next_state = yy_nxt[yy_rmap[yy_state]][yy_cmap[yy_lookahead]];
			if (YY_EOF == yy_lookahead && true == yy_initial) {
			//return the special symbol at the end of file. Maybe executed more than once.
	return(symbol("EOF"));
			}
			if (YY_F != yy_next_state) {
				yy_state = yy_next_state;
				yy_initial = false;
				yy_this_accept = yy_acpt[yy_state];
				if (YY_NOT_ACCEPT != yy_this_accept) {
					yy_last_accept_state = yy_state;
					yy_mark_end();
				}
			}
			else {
				if (YY_NO_STATE == yy_last_accept_state) {
					throw (new Error("Lexical Error: Unmatched Input."));
				}
				else {
					yy_anchor = yy_acpt[yy_last_accept_state];
					if (0 != (YY_END & yy_anchor)) {
						yy_move_end();
					}
					yy_to_mark();
					switch (yy_last_accept_state) {
					case 1:
						
					case -2:
						break;
					case 2:
						{ return symbol("COMMA"); }
					case -3:
						break;
					case 3:
						{ return symbol("SEMI"); }
					case -4:
						break;
					case 4:
						{ return symbol("LPAREN"); }
					case -5:
						break;
					case 5:
						{ return symbol("RPAREN"); }
					case -6:
						break;
					case 6:
						{ return symbol("LBRACKET"); }
					case -7:
						break;
					case 7:
						{ return symbol("RBRACKET"); }
					case -8:
						break;
					case 8:
						{ return symbol("MINUS"); }
					case -9:
						break;
					case 9:
						{ return symbol("ASSIGN"); }
					case -10:
						break;
					case 10:
						{}
					case -11:
						break;
					case 11:
						{ return symbol("LEX_ERROR"); }
					case -12:
						break;
					case 12:
						{}
					case -13:
						break;
					case 13:
						{ return symbol("IDENT");}
					case -14:
						break;
					case 14:
						{return symbol("PLAIN_DOUBLE");}
					case -15:
						break;
					case 15:
						{ return symbol("STRING");}
					case -16:
						break;
					case 16:
						{  return symbol("HEX_DOUBLE");}
					case -17:
						break;
					case 18:
						{ return symbol("LEX_ERROR"); }
					case -18:
						break;
					case 19:
						{return symbol("PLAIN_DOUBLE");}
					case -19:
						break;
					case 21:
						{ return symbol("LEX_ERROR"); }
					case -20:
						break;
					case 22:
						{return symbol("PLAIN_DOUBLE");}
					case -21:
						break;
					case 24:
						{ return symbol("LEX_ERROR"); }
					case -22:
						break;
					case 26:
						{ return symbol("LEX_ERROR"); }
					case -23:
						break;
					default:
						yy_error(YY_E_INTERNAL,false);
					case -1:
					}
					yy_initial = true;
					yy_state = yy_state_dtrans[yy_lexical_state];
					yy_next_state = YY_NO_STATE;
					yy_last_accept_state = YY_NO_STATE;
					yy_mark_start();
					yy_this_accept = yy_acpt[yy_state];
					if (YY_NOT_ACCEPT != yy_this_accept) {
						yy_last_accept_state = yy_state;
						yy_mark_end();
					}
				}
			}
		}
	}
}
