
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Sep 27 14:45:16 PDT 2006
//----------------------------------------------------

package coho.interp;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int MINUS = 12;
  public static final int IDENT = 4;
  public static final int SEMI = 11;
  public static final int EOF = 0;
  public static final int PLAIN_DOUBLE = 2;
  public static final int STRING = 5;
  public static final int RBRACKET = 9;
  public static final int LEX_ERROR = 14;
  public static final int ASSIGN = 13;
  public static final int COMMA = 10;
  public static final int error = 1;
  public static final int HEX_DOUBLE = 3;
  public static final int RPAREN = 7;
  public static final int LBRACKET = 8;
  public static final int LPAREN = 6;

  /* non terminals */
  static final int assignment = 2;
  static final int col = 6;
  static final int colTail = 7;
  static final int stateList = 8;
  static final int rowTail = 5;
  static final int statement = 1;
  static final int $START = 0;
  static final int expr = 3;
  static final int row = 4;
}

